# Functions

In [1]:
a = 1
b = 2
a+b

3

$ a + (b)^2 $

In [2]:
a+b**2

5

$ (a \times 2) + b^2 $

In [3]:
a*2+b**2

6

In [5]:
print("a is equal to", a)

a is equal to 1


In [6]:
print("b is equal to", b)

b is equal to 2


In [7]:
def add_number(x, y):
    return x+y

add_number(1,2)

3

In [8]:
def add_number(a, b):
    return ((a)**2 + b)*2

add_number(1,2)

6

In [9]:
def add_number(a, b):
    return ((a)**2 + b)*2

add_number(81,27)

13176

In [11]:
def add_number(x, y, z = None):
    if (z == None):
        return x+y
    else:
        return x+y+z
    
print(add_number(1,2))
print(add_number(1,2,3))

3
6


In [12]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true!
3


In [13]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

3

I played a bit more than what those videos were showing!!! :)

# Types and Sequences

In [14]:
type('This is a string')

str

In [15]:
type(None)

NoneType

In [16]:
type(1)

int

In [17]:
type(1.0)

float

In [18]:
type(add_numbers)

function

In [19]:
x = (1, 'a', 2, 'b')
type(x)

tuple

In [20]:
x = [1, 'a', 2, 'b']
type(x)

list

In [21]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [22]:
for item in x:
    print(item)

1
a
2
b
3.3


In [23]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


In [24]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [25]:
[1]*3

[1, 1, 1]

In [26]:
x = 'This is a string'
print(x[0]) 
print(x[0:1]) 
print(x[0:2]) 

T
T
Th


In [27]:
x[-7]

' '

In [28]:
x[-8]

'a'

In [30]:
x[-8:-2]

'a stri'

In [31]:
x[-4:-2]

'ri'

In [33]:
x[6:]

's a string'

In [34]:
firstname = 'Aru'
lastname = 'Bhardwaj'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Aru' in firstname)

Aru Bhardwaj
AruAruAru
True


In [35]:
firstname = 'Aru Bhardwaj'.split(' ')[0] 
lastname = 'Aru Bhardwaj'.split(' ')[-1] 
print(firstname)
print(lastname)

Aru
Bhardwaj


In [39]:
x = {'Aru Bhardwaj': 'arubhardwaj@hotmail.com', 'Bill Gates': 'billg@microsoft.com'}
x['Aru Bhardwaj'] 

'arubhardwaj@hotmail.com'

# More on Strings

In [40]:
print('Aru' + str(2))

Aru2


In [41]:
print('Aru', 2)

Aru 2


# Reading CSV Files

In [62]:
import pandas as pd
import csv


In [63]:
csvfile = pd.read_csv("E:\mpg.csv")

In [68]:
mpg = list(csv.DictReader(csvfile))

mpg[:3]

[OrderedDict([('mpg', 'cylinders')]),
 OrderedDict([('mpg', 'displacement')]),
 OrderedDict([('mpg', 'horsepower')])]

In [69]:
len(mpg)

8

# Dates and Times

In [70]:
import datetime as dt
import time as tm

In [71]:
tm.time()

1598872817.15

In [72]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 8, 31, 16, 50, 25, 449390)

In [73]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second 

(2020, 8, 31, 16, 50, 25)

In [74]:
dtnow.day, dtnow.month, dtnow.year, dtnow.hour, dtnow.minute, dtnow.second 

(31, 8, 2020, 16, 50, 25)

In [79]:
print("Today's date is", dtnow.day, dtnow.month, dtnow.year)

Today's date is 31 8 2020


In [80]:
print("Today's date is", dtnow.day, "/", dtnow.month, "/", dtnow.year)

Today's date is 31 / 8 / 2020


# Objects and map()

In [81]:
class Person:
    department = 'School of Economics'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [83]:
person = Person()
person.set_name('Aru Bhardwaj')
person.set_location('India')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Aru Bhardwaj live in India and works in the department School of Economics


In [86]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [88]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In Video question

In [89]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

# Lambda and List Comprehensions

In [96]:
my_function = lambda a,b,c:a+b

In [97]:
my_function(1,2,3)

3

In [98]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

# Working with Numpy

In [99]:
import numpy as np

In [100]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [101]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [104]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [105]:
m.shape

(2, 3)

In [109]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [111]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [112]:

o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [113]:
np.ones((3, 2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [116]:
np.zeros((2, 3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:

p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [119]:
np.vstack([p, 2*p])


array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [120]:
np.hstack([p, 2*p])


array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

In [121]:
print(x+y)
print(x-y)

[5 7 9]
[-3 -3 -3]


In [122]:
z = np.array([y, y**2])
print(np.shape(z))
print(len(z))

(2, 3)
2


In [123]:
z = np.array([y, y**2])
z


array([[ 4,  5,  6],
       [16, 25, 36]])

In [124]:
a = np.array([-4, -2, 1, 3, 5])


In [125]:
a.sum()

3

In [126]:
a.max()

5

In [127]:
r[0:6,::-7]


NameError: name 'r' is not defined